steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - run_pipeline
      - --source=.
      - --region=us-central1
      - --platform=managed
      - --allow-unauthenticated
