BASE_URL = "https://www.durhamnc.gov/AgendaCenter/City-Council-4"
GOOGLE_SERVICE_ACCOUNT = "durham-city-council-f476f12b4cac.json"
PROJECT_ID = "durham-city-council"
DATASET_ID = "minutes"
SUBJECT_TABLE_ID = f"{DATASET_ID}.subject"
MOTION_TABLE_ID = f"{DATASET_ID}.motion"
VOTE_TABLE_ID = f"{DATASET_ID}.vote"
MEMBER_TABLE_ID = f"{DATASET_ID}.member"
